### ISSUE TITLE
The Page

### ISSUE THREAD

**Issue by duncangeere** [howwegettonext/endangeredlanguages#1]
Will be based on this template
![image](https://user-images.githubusercontent.com/11523915/37094044-cd76c84e-2211-11e8-9d85-2535416709c2.png)

**Comment by edenbrack** [comment]
![endangeredlanguages-mockup-3](https://user-images.githubusercontent.com/15315009/37210365-6f8e43de-23a0-11e8-8a79-71128a28715a.png)

**Comment by duncangeere** [comment]
We're looking quite good here. All the copy is in (though it needs proofing). Just a few layout/spacing tweaks to sort. I made a few misc changes in the CSS to accommodate the things I was putting in, but feel free to revert any of them and/or make any other changes needed so that the page looks lovely!

**Comment by duncangeere** [comment]
Just need to fix the Safari bug, and then I think we're done!
