### ISSUE TITLE
Continent Index

### ISSUE THREAD

**Issue by duncangeere** [howwegettonext/endangeredlanguages#4]
Sort the language bubbles into categories by continent. 
Based on: https://bl.ocks.org/mbostock/1804919 - danger v3 code

**Comment by duncangeere** [comment]
First step will be to add continent data to the spreadsheet, based on country

**Comment by edenbrack** [comment]
If you could add a caption to each of these continent charts with their respective continent names that'd be ace!

**Comment by duncangeere** [comment]
I've added the charts, but not the captions yet. Should be trivial though!

**Comment by duncangeere** [comment]
Done!
