### ISSUE TITLE
Focus languages

### ISSUE THREAD

**Issue by duncangeere** [howwegettonext/endangeredlanguages#7]
Three of them, a bit like this:
![image](https://user-images.githubusercontent.com/11523915/37210580-8c4e15c2-23a9-11e8-8030-57b0ab6f5fdf.png)
Made in Illustrator.

**Comment by edenbrack** [comment]
https://www.amcharts.com/svg-maps/ Go here for SVGs of countries for these graphics.

**Comment by duncangeere** [comment]
I've [written up three languages](https://docs.google.com/document/d/1xTTsUmV7s1rKG7R4TxTqIY-z66xp5eEwhEGPnjocz0M/edit?usp=sharing
) and made graphics for them. The problem is that I'm not sure they're the MOST interesting languages I could have chosen. As such, we'll probably revisit this (and Ian might help if he has time, because I think fresh eyes would help on this), but we can use this as a placeholder for the time being I guess!

![south italian](https://user-images.githubusercontent.com/11523915/37589701-5d7ffff2-2b66-11e8-96b9-f1caf0f38bcd.png)
![tape](https://user-images.githubusercontent.com/11523915/37589702-5d985c46-2b66-11e8-8d70-6ee0f13344c0.png)
![highland chontal](https://user-images.githubusercontent.com/11523915/37589703-5db0c93e-2b66-11e8-8973-b6da8dd8e967.png)

**Comment by duncangeere** [comment]
Done!
