### ISSUE TITLE
Your nearest endangered language

### ISSUE THREAD

**Issue by duncangeere** [howwegettonext/endangeredlanguages#8]
Small map, single dot. Bit of maths to work out closest language from lat/lon. Looks a bit like this:
![image](https://user-images.githubusercontent.com/11523915/37210610-a88744e8-23a9-11e8-9bfd-e9d0c90c4aec.png)

**Comment by edenbrack** [comment]
This map doesn't need to be interactive/zoomable.

**Comment by duncangeere** [comment]
The code for calculating the language is written and working great. You can play with it [here](http://interactive.howwegettonext.com/endangeredlanguages/test_nearest.html). All we need to do is the geocoding and the interface - the map, the dot and the text.

**Comment by duncangeere** [comment]
The interface is pretty much complete, it just needs to integrated with the page.

**Comment by duncangeere** [comment]
Done!
